### ISSUE TITLE
asyncio.get_event_loop is deprecated

### ISSUE THREAD

**Issue by EvanSucksAtCode** [priyankark/SensorStreamServer#10]
asyncio.get_event_loop is deprecated. Attached is the updated server.py
Requires websockets version 10.4
[server.py.zip](https://github.com/priyankark/SensorStreamServer/files/10317261/server.py.zip)

**Comment by priyankark** [comment]
Thank you @EvanSucksAtCode ! Mind raising a PR, I'll check the code out in the meantime.

**Comment by priyankark** [comment]
Thank you once again @EvanSucksAtCode (you don't suck at code). I have made the changes and credited you. Thanks for giving Sensor Stream App a try.
