### ISSUE TITLE
Fail to connect 

### ISSUE THREAD

**Issue by darld** [priyankark/SensorStreamServer#3]
![Screenshot_2021-11-28-09-38-56-913_com sensorsensei](https://user-images.githubusercontent.com/46642509/143725625-8db60308-7085-4809-8646-b569b530a76c.jpg)
 Also the app is crashed when start the gps sensor 

Phone : redmi note 10

**Comment by priyankark** [comment]
For the first issue: 
Is your PC and phone on the same network? Can you share a screenshot of the server as well? And if you have a firewall on your PC, that can block connections as well leading to the same error. Try disabling the firewall if any for the duration of usage

**Comment by namKolorfuL** [comment]
Hi @priyankark , I'm having the same issue. I have my phone and pc connected to the same wifi and, block all firewalls and the alert still persists.
![image](https://user-images.githubusercontent.com/55870032/147786074-39b415a2-8b15-4ac3-94e7-9b5c34cfc6a8.png)
![z3068677737934_c691fafb6268a4e6392df7519313063d](https://user-images.githubusercontent.com/55870032/147786085-8d79f6b7-2dc9-41b7-a406-e8ddb7f2ad9d.jpg)

**Comment by priyankark** [comment]
That's super weird. Can you check if your PC has multiple ip addresses and try the other ones. Example: 192.168.x.x:5000

**Comment by NoLoPhe** [comment]
I got the same error and fixed it as follows:

the first time when running CMD ipconfig
IPv4 Address there are two values: 172.16.0.2 and 192.168.1.2
![image](https://user-images.githubusercontent.com/60751518/149385049-5b094971-3c8e-40f8-ad83-614e12b174e8.png)

I turned off the firewall > forget about wifi > enter passwifi > reconnected

IPv4 Address there are one values: 192.168.1.2
![image](https://user-images.githubusercontent.com/60751518/149385810-df4ca09d-efbb-4780-85d2-129fbd900b0d.png)

Done! 192.168.1.2:5000

**Comment by priyankark** [comment]
Thanks for helping @NoLoPhe!! Hope the above discussion helps @darld and @namKolorfuL
